---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-app-deployment
  labels:
    app: uptime-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: uptime-app
  template:
    metadata:
      labels:
        app: uptime-app
    spec:
      containers:
      - name: uptime-app
        image: k8s.gcr.io/echoserver:1.10
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: uptime-app-service
  labels:
    app: uptime-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: uptime-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-app-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: uptime.alexelsh.nl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: uptime-app-service
            port:
              number: 80
