---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  namespace: red-app
  labels:
    app: echo-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
      - name: echo-server
        image: k8s.gcr.io/echoserver:1.10
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echo-server-service
  namespace: red-app
  labels:
    app: echo-server
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: echo-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-server-ingress
  namespace: red-app
  annotations:
    kubernetes.io/ingress.class: "red-nginx"
    external-dns.alpha.kubernetes.io/hostname: red-tenant-one.alexelsh.nl
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  rules:
  - host: red-tenant-one.alexelsh.nl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: echo-server-service
            port:
              number: 80
