#Define a service account
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: common-controls
  namespace: common-controls
---
#RBAC rules for the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: common-controls
rules:
- apiGroups: [""]
  resources: ["services", "endpoints","nodes", "pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "watch", "list"]
# Role binding: Bind the new RBAC to the service account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: common-controls-crb
  namespace: common-controls  # This must be the namespace where ExternalDNS watches
subjects:
- kind: ServiceAccount
  name: common-controls-sa
  namespace: common-controls  # ExternalDNS runs here
roleRef:
  kind: ClusterRole
  name: common-controls-cr
  apiGroup: rbac.authorization.k8s.io
# Deploy external dns with proxy enabled as we don't want to enable SSL certificates on the cluster. We are already using cloud flare.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: common-controls-dns
  namespace: common-controls-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: common-controls-dns
  template:
    metadata:
      labels:
        app: common-controls-dns
    spec:
      serviceAccountName: common-controls-dns
      containers:
      - name: common-controls-dns
        image: registry.k8s.io/external-dns/external-dns:v0.15.1
        args:
          - --source=ingress
          - --source=service
          - --provider=cloudflare
          - --cloudflare-proxied           # Optional: enable Cloudflare proxy (orange cloud)
          - --policy=sync
          - --log-level=info
          - --namespace=parca #This is terrible honestly, I need to use a domain-filter with a different domain but ok...
          - --txt-owner-id=common-controls
        env:
        - name: CF_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-api-token
              key: api-token
