#Define a service account
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns-analyzer
  namespace: analyzer-control
---
#RBAC rules for the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns-analyzer
rules:
- apiGroups: [""]
  resources: ["services", "endpoints","nodes", "pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "watch", "list"]
# Role binding: Bind the new RBAC to the service account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-analyzer-viewer
  namespace: analyzer-app  # This must be the namespace where ExternalDNS watches
subjects:
- kind: ServiceAccount
  name: external-dns-analyzer
  namespace: analyzer-control  # ExternalDNS runs here
roleRef:
  kind: ClusterRole
  name: external-dns-analyzer
  apiGroup: rbac.authorization.k8s.io
# Deploy external dns with proxy enabled as we don't want to enable SSL certificates on the cluster. We are already using cloud flare.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-analyzer
  namespace: analyzer-control
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-dns-analyzer
  template:
    metadata:
      labels:
        app: external-dns-analyzer
    spec:
      serviceAccountName: external-dns-analyzer
      containers:
      - name: external-dns-analyzer
        image: registry.k8s.io/external-dns/external-dns:v0.15.1
        args:
          - --source=ingress
          - --source=service
          - --provider=cloudflare
          - --cloudflare-proxied           # Optional: enable Cloudflare proxy (orange cloud)
          - --policy=sync
          - --log-level=info
          - --namespace=analyzer-app
          - --txt-owner-id=analyzer
        env:
        - name: CF_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-api-token
              key: api-token
