name: Deploy Ingress
on:
  push:
  workflow_dispatch:

jobs:
  tech-tenant-app:
    needs: kubernetes-infra
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Configure Kubeconfig
        run: aws eks update-kubeconfig --name ephemral-cluster --region ${{ secrets.AWS_REGION }}
      
      - name: deploy application
        run: |
          kubectl apply -f tech-tenant-app.yaml 
